### ISSUE TITLE
Incorrect instrumentation causes loss of symbolic information

### ISSUE THREAD

**Issue by DonatoClun** [DeepseaPlatform/coastal#42]
Consider this simple example
```java
package mine;
import za.ac.sun.cs.coastal.Symbolic;
public class MyExample {
	public static void main(String[] args) {
		test("a");
	}
	public static void test(String body) {
		if (AClass.INST == null)
			Symbolic.mark(-1);
		else
			Symbolic.mark(1);
	}
}
```
using this other class
```java
package mine;
public final class AClass {
	public static final AClass INST = new AClass();
	public AClass() { }
}
```
analyzed with Coastal with these settings
```
coastal.target.main = mine.MyExample
coastal.target.instrument = mine.*
coastal.settings.trace-all = true
coastal.target.trigger = mine.MyExample.test(S: String)
```

The condition that I expect to see in the path condition is `1!=0` because:
- AClass is loaded
- in the initialization a new instance is created
- the JVM executes a PUTSTATIC that makes Coastal  save in instanceData the "reference" to the new instance (let's say 1).
- when if (AClass.INST == null) is executed, a GETSTATIC fetch the reference and the condition becomes 1==0, so the else branch is taken, etc.

What actually happens is that in the condition is `$1!=0`.

After a bit of investigation I think I found the issue.

This is the trigger method instrumented and decompiled:
```java
  public static void test(String var0) {
    if (!VM.getRecordingMode()) {
      VM.triggerMethod(3, 0, (boolean)1);
      var0 = VM.getConcreteString(0, 0, 0, var0);
    } else {
      VM.startMethod(3, 1);
    }

    VM.linenumber(6, 8, "mine.MyExample");
    VM.fieldInsn(7, 178, "mine/AClass", "INST", "Lmine/AClass;"); // 1 <================
    AClass var10000 = AClass.INST; // 2 <==============================================
    VM.jumpInsn(8, 199);
    if (var10000 == null) {
      VM.postJumpInsn(8, 199);
      VM.linenumber(8, 9, "mine.MyExample");
      VM.insn(9, 2);
      VM.mark(-1);
      VM.jumpInsn(10, 167);
    } else {
      VM.linenumber(10, 11, "mine.MyExample");
      VM.insn(11, 4);
      VM.mark(1);
    }

    VM.linenumber(11, 12, "mine.MyExample");
    VM.insn(12, 177);
  }
```
In the highlighted lines looks like the GETSTATIC (fieldInsn with opcode 178) is called before the first appearence of AClass, so before it's initialized. The value is not found in instanceData, and as a result a fresh new variable is pushed on the stack.

As a countercheck, I tried to use AClass before the `if`, and as expected, it worked correctly.

**Comment by jacogeld** [comment]
To fix it, the instrumentation was moved after the concrete instruction.  This means that the JVM sees that it needs to load class AClass before the symbolic equivalent of the GETSTATIC instruction is executed.

This works for this example, but it may introduce other errors.  Also, instructions may not work correctly.  Further tests are required.

Re the ``(1!=0)`` condition, it is not added to the path condition because coastal.settings.constant-elimination=true.
